# Phân tích mạng lưới tương quan

## Giới thiệu

...

## Bối cảnh thí nghiệm

...

## Thăm dò dữ liệu

...

```{r}
library(tidyverse)

df = read.csv('PCOS_IR.csv', 
              sep = ';', 
              dec = ',',
              fileEncoding = 'UTF-8-BOM')

df$Group = as.factor(df$Group)

df%>%filter(.$Group!="PCOS")%>%
  mutate(Class = if_else(.$Group=="Norm",
                         "Normal",
                         "PCOS"))%>%
  gather(c(2:16), 
         key = "Features", 
         value="Value")%>%
  group_by(Class,
           Features)%>%
  summarise(n = n(),
            Mean = mean(Value),
            sd = sd(Value),
            Median = median(Value),
            p5 = quantile(Value, 0.05),
            p95 = quantile(Value, 0.95))%>%
  knitr::kable(digits = 2)
```

## Ma trận tương quan

...

```{r}
neg_df = df%>%
  dplyr::filter(.$Group=="Norm")%>%
  dplyr::select(Age,BMI,
                AMH,AFC,OSI,
                Gluc,F_INS,HOMA_IR,
                LH,FSH,E2,P,
                PRL,`T`,TSH)
  
pos_df = df%>%
  dplyr::filter(.$Group=="IR")%>%
  dplyr::select(Age,BMI,
                AMH,AFC,OSI,
                Gluc,F_INS,HOMA_IR,
                LH,FSH,E2,P,
                PRL,`T`,TSH)

cormat_pos = cor(method="pearson",
                 as.matrix(pos_df))

cormat_neg = cor(method="pearson",
                 as.matrix(neg_df))
```

...

```{r}
library(corrplot)
library(RColorBrewer)

cormat_pos %>% corrplot(.,order="hclust",
                     type="lower",
                     method="color",
                     diag	= F,
                     addCoef.col = "black",
                     tl.col="black", 
                     title = "PCOS",
                     tl.srt=45,
                     tl.cex=0.8,
                     number.cex	= 0.5,
                     col=rev(brewer.pal(n=10, 
                                        name="Spectral")))
```

...

```{r}
cormat_neg%>%corrplot(.,order="hclust",
                   type="lower",
                   method="color",
                   diag	= F,
                   addCoef.col = "black",
                   tl.col="black", 
                   title = "Normal",
                   tl.srt=45,
                   tl.cex=0.8,
                   number.cex	= 0.5,
                   col=rev(brewer.pal(n=10,
                                      name="Spectral")))
```

...

```{r}
cor.mtest <- function(mat, ...) {
  mat <- as.matrix(mat)
  n <- ncol(mat)
  p.mat<- matrix(NA, n, n)
  diag(p.mat) <- 0
  for (i in 1:(n - 1)) {
    for (j in (i + 1):n) {
      tmp <- cor.test(mat[, i], mat[, j], ...)
      p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
    }
  }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}

corsig_pos = cor.mtest(pos_df)
corsig_neg = cor.mtest(neg_df)
```

...

```{r}
corrplot(cormat_pos, 
         col= pals::coolwarm(100),
         method="pie",
         type="upper",
         order="hclust",
         p.mat = corsig_pos, 
         title = "PCOS",
         sig.level = 0.05,
         insig = "blank",
         tl.col="black", 
         tl.srt=45,
         tl.cex=0.8,
         diag=FALSE
         )
```

...

```{r}
corrplot(cormat_neg, 
         col= pals::coolwarm(100),
         method="pie",
         type="upper",
         order="hclust",
         p.mat = corsig_neg, 
         title = "Normal",
         sig.level = 0.05,
         insig = "blank",
         tl.col="black", 
         tl.srt=45,
         tl.cex=0.8,
         diag=FALSE
         )
```

...

## Sơ đồ mạng lưới tương quan

...

```{r}
m=cormat_pos
diag(m)<-0
cor_pos_df = data.frame(row=rownames(m)[row(m)[upper.tri(m)]], 
                        col=colnames(m)[col(m)[upper.tri(m)]], 
                        corr=m[upper.tri(m)])

m=corsig_pos
diag(m)<-0
sig_pos_df = data.frame(row=rownames(m)[row(m)[upper.tri(m)]], 
                        col=colnames(m)[col(m)[upper.tri(m)]], 
                        corr=m[upper.tri(m)])

cor_pos_df$sig = sig_pos_df$corr
rm(sig_pos_df)

names(cor_pos_df)=c("from","to","r","sig")

reduced_pos = cor_pos_df%>%
  filter(sig<0.05)

reduced_pos<-reduced_pos%>%
  mutate(Strength = if_else(abs(reduced_pos$r)>0.5,
                            "Strong","Weak"),
         Direction =if_else(reduced_pos$r>0,
                            "Pro","Inv"))

library(igraph)

graph_pos<-graph_from_data_frame(reduced_pos,
                                 directed = F)

plot(graph_pos)
```
...

```{r}
library(intergraph)
library(network)
library(statnet)

pos_net <- asNetwork(graph_pos)

plot(pos_net,displaylabel=T,
     label.cex=0.8)
```

...

```{r}
set.vertex.attribute(pos_net, "Physio",
                     c("A","A","Ov","Ov","Ov",
                       "Glu","H","H","Glu","Glu",
                       "H","H","H","H"))
```

...

```{r}
m=cormat_neg
diag(m)<-0
cor_neg_df = data.frame(row=rownames(m)[row(m)[upper.tri(m)]], 
                        col=colnames(m)[col(m)[upper.tri(m)]], 
                        corr=m[upper.tri(m)])

m=corsig_neg
diag(m)<-0
sig_neg_df = data.frame(row=rownames(m)[row(m)[upper.tri(m)]], 
                        col=colnames(m)[col(m)[upper.tri(m)]], 
                        corr=m[upper.tri(m)])

cor_neg_df$sig = sig_neg_df$corr
rm(sig_neg_df)

names(cor_neg_df)=c("from","to","r","sig")

reduced_neg = cor_neg_df%>%
  filter(sig<0.05)

reduced_neg<-reduced_neg%>%
  mutate(Strength = if_else(abs(reduced_neg$r)>0.5,
                            "Strong","Weak"),
         Direction = if_else(reduced_neg$r>0,
                             "Pro","Inv"))

graph_neg<-graph_from_data_frame(reduced_neg,
                                 directed = F)

neg_net <- asNetwork(graph_neg)

plot(neg_net,displaylabel=T,
     label.cex=0.8)

set.vertex.attribute(neg_net, "Physio",
                     c("A","Ov","Ov",
                       "Glu","Glu","Ov","H",
                       "Glu","H","H","H"))
```

## Phân tích cấu trúc mạng lưới tương quan

...

```{r}
summary(pos_net,
        print.adj=F)
```
...

```{r}
summary(neg_net,
        print.adj=FALSE)
```

...

```{r}
diameter= function(network) {
  component.largest(network,
                    result="graph")%>%
    geodist()->gd
  max(gd$gdist)
  }

diameter(pos_net)
diameter(neg_net)
```
...

```{r}
gtrans(pos_net)
```

```{r}
gtrans(neg_net)
```

...

```{r}
cent_df = tibble(Vertex = c(neg_net %v% "vertex.names",
                                pos_net %v% "vertex.names"),
                     
                     Physio = c("A","Ov","Ov","Glu",
                                "Glu","Ov","H",
                                "Glu","H","H","H",
                                "A","A","Ov",
                                "Ov","Ov","Glu",
                                "H","H","Glu","Glu",
                                "H","H","H","H"
                                ),
                     
                     Status = c(rep("Normal",11),rep("PCOS",14)),
                     
                     Degree = c(degree(pos_net, 
                                       gmode="graph"),
                                degree(neg_net, 
                                       gmode="graph")),
                     
                     Closeness = c(closeness(pos_net,
                                             gmode="graph"),
                                   closeness(neg_net,
                                             gmode="graph")),
                     Beetweeness = c(betweenness(pos_net,
                                                 gmode="graph"),
                                     betweenness(neg_net,
                                                 gmode="graph")),
                     Eigen = c(evcent(pos_net, 
                                      gmode="graph"),
                               evcent(neg_net, 
                                      gmode="graph")),
                     
                     BonPow = c(bonpow(pos_net, 
                                       gmode="graph"),
                                bonpow(neg_net, 
                                       gmode="graph")),
                     
                     InfoCent = c(infocent(pos_net, 
                                           gmode="graph"),
                                  infocent(neg_net, 
                                           gmode="graph"))
                     )
```

...

```{r}
cent_df%>%
  gather(c(4:9), 
         key = "Features", 
         value="Value")%>%
  group_by(Status, 
           Physio, 
           Features)%>%
  summarise(n = n(),
            Median = median(Value),
            p5 = quantile(Value, 0.05),
            p95 = quantile(Value, 0.95))%>%
  knitr::kable(digits = 2)
```

```{r}
cent_df%>%
  gather(Degree:InfoCent,
         key="Score",
         value="Centrality")%>%
  ggplot(aes(x=Vertex,
             y=Centrality,
             fill=Status))+
  geom_point(stat="identity",
             size=2,
             shape=21,
             col="black")+
  theme_bw()+
  coord_flip()+
  facet_wrap(~Score,
             ncol=3,
             scales="free")
```

```{r}
cent_df%>%
  gather(Degree:InfoCent,
         key="Score",
         value="Centrality")%>%
  ggplot(aes(x=Physio,
             y=Centrality,
             fill=Status))+
  geom_boxplot(alpha=0.7)+
  theme_bw()+
  coord_flip()+
  facet_wrap(~Score,
             ncol=2,
             scales="free")
```

```{r}
cent_df%>%
  gather(Degree:InfoCent,
         key="Score",
         value="Centrality")%>%
  ggplot(aes(x=Status,
             y=Centrality,
             fill=Physio))+
  geom_boxplot(alpha=0.7)+
  theme_bw()+
  coord_flip()+
  facet_wrap(~Score,
             ncol=2,
             scales="free")
```

...

```{r}
# Cutpoint
cp_pos <- cutpoints(pos_net,
                    mode="graph",
                    return.indicator=TRUE)

gplot(pos_net,
      gmode="graph",
      label=pos_net%v%"vertex.names",
      label.cex=.8,
      pad=1,
      vertex.col=cp_pos+1,
      jitter=FALSE,
      displaylabels=TRUE)
```

...

## Yếu tố mỹ thuật

...

```{r}
op <- par(mar=c(0,0,2,0),
          mfrow=c(2,3))

gplot(pos_net,
      gmode="graph",
      mode="circle",
      edge.col="grey",
      vertex.col = "red",
      vertex.cex=1,
      main="Circle")

gplot(pos_net,
      gmode="graph",
      mode="random",
      edge.col="grey",
      vertex.col = "gold",
      vertex.cex=1,
      main="Random layout")

gplot(pos_net,
      gmode="graph",
      mode="fruchtermanreingold",
      edge.col="grey",
      vertex.col = 3,
      vertex.cex=1,
      main="Fruchterman-Reingold")

gplot(pos_net,
      gmode="graph",
      mode="spring",
      edge.col="grey",
      vertex.col = 4,
      vertex.cex=1,
      main="Spring")

gplot(pos_net,
      gmode="graph",
      mode="eigen",
      edge.col="grey",
      vertex.col = 6,
      vertex.cex=1,
      main="Eigenstructure")

gplot(pos_net,
      gmode="graph",
      mode="kamadakawai",
      edge.col="grey",
      vertex.col = "black",
      vertex.cex=1,
      main="Kamadakawai")
```

...

```{r}
op <- par(mar=c(0,0,1,0),
          mfrow=c(2,2))

coords<-plot(pos_net,
             label=pos_net%v%"vertex.names",
             label.cex=.5,
             pad=1)

deg <- degree(pos_net,
              gmode="graph")
cls <- closeness(pos_net,
                 gmode="graph")
bet <- betweenness(pos_net,
                   gmode="graph")

gplot(pos_net, 
      vertex.cex=log(deg), 
      label.cex=0.8,
      mode="circle",
      label=pos_net%v%"vertex.names",
      vertex.col=rgb(deg/max(deg),
                     0.2,
                     1-deg/max(deg)),
      gmode="graph",
      coord=coords)

gplot(pos_net, 
      vertex.cex=2*cls, 
      label.cex=0.8,
      mode="circle",
      label=pos_net%v%"vertex.names",
      vertex.col=rgb(cls/max(cls),
                     0.3,
                     1.2-cls/max(cls)),
      gmode="graph",
      coord=coords)

gplot(pos_net, 
      vertex.cex=1.2*log(sqrt(bet+1)), 
      label.cex=0.8,
      label=pos_net%v%"vertex.names",
      vertex.col=rgb(bet/max(bet),
                     1-bet/max(bet),
                     0.1),
      gmode="graph",
      coord=coords)
```

...

```{r}
par(mar=c(0,0,1,0),
    mfrow=c(1,2))

edge_dir <- as.factor(pos_net%e%"Direction")
edge_dir_pal <- c("blue","red")

plot(pos_net,
     label=pos_net%v%"vertex.names",
     displaylabels=T,
     label.cex=0.8,
     vertex.cex=3*cls,
     vertex.col=rgb(cls/max(cls),
                    0.3,
                    1.2-cls/max(cls)),
     edge.col=edge_dir_pal[edge_dir],
     edge.lwd=1,
     edge.label=edge_dir,
     edge.label.cex=0.5,
     edge.label.col=edge_dir_pal[edge_dir],
     mode="kamadakawai")

edge_val <- as.factor(round(pos_net%e%"r",2))

edge_val_pal <- pals::coolwarm(length(edge_val))

plot(pos_net,
     label=pos_net%v%"vertex.names",
     displaylabels=T,
     vertex.cex=3*cls,
     vertex.col=rgb(cls/max(cls),
                    0.3,
                    1.2-cls/max(cls)),
     label.cex=0.8,
     edge.col=edge_val_pal[edge_val],
     edge.lwd=1,
     edge.label=edge_val,
     edge.label.cex=0.6,
     edge.label.col=edge_val_pal[edge_val],
     mode="kamadakawai")
```

```{r}
edge_val_pos <- as.factor(round(pos_net%e%"r",2))

edge_val_pos_pal <- pals::coolwarm(length(edge_val_pos))

edge_val_neg <- as.factor(round(neg_net%e%"r",2))

edge_val_neg_pal <- pals::coolwarm(length(edge_val_neg))

deg_pos <- degree(pos_net,
                  gmode="graph")

deg_neg <- degree(neg_net,
                  gmode="graph")

par(mar=c(0,0,1,0),
    mfrow=c(1,2))

plot(pos_net,
     gmode="graph",
     mode="kamadakawai",
     label=pos_net%v%"vertex.names",
     label.cex=.9,
     pad=1,
     vertex.col=rgb(deg_pos/max(deg_pos),
                    0.2,
                    1-deg_pos/max(deg_pos)),
     vertex.cex=log(deg_pos)*0.9, 
     edge.col=edge_val_pos_pal[edge_val_pos],
     edge.lwd=1,
     edge.label=edge_val_pos,
     edge.label.cex=0.5,
     edge.label.col=edge_val_pos_pal[edge_val_pos])

title("PCOS")

plot(neg_net,gmode="graph",
     label=pos_net%v%"vertex.names",
     mode="kamadakawai",
     label.cex=.9,
     pad=1,
     vertex.col=rgb(deg_neg/max(deg_neg),
                    0.2,
                    1-deg_neg/max(deg_neg)),
     vertex.cex=log(deg_neg)*0.9, 
     edge.col=edge_val_neg_pal[edge_val_neg],edge.lwd=1,
     edge.label=edge_val_neg,
     edge.label.cex=0.5,
     edge.label.col=edge_val_neg_pal[edge_val_neg])

title("Normal")
```

## Thông điệp rút gọn làm hành trang

...
