# Thí nghiệm khảo sát lặp lại: Mô hình GEE

## Giới thiệu

...

## Bối cảnh của thí nghiệm

...

## Công cụ cho quy trình

...

```{r,echo = FALSE, message = FALSE,warning=FALSE}
library(tidyverse)
library(ggridges)

library(marginaleffects)
library(geepack)
library(broom)
```

...

```{r,echo = FALSE, message = T,warning=T}

df <- read.csv('LH_PPOS.csv', 
               sep = ';', 
               dec= ',', 
               fileEncoding = 'UTF-8-BOM')%>%
  na.omit()

df$ID = as.factor(df$ID)
df$Method = as.factor(df$Method)
df$Timepoint = as.factor(df$Timepoint)

df_mod <- df %>% 
  dplyr::select(ID, Timepoint, Method, LH) %>% 
  na.omit()

df%>%sample_frac(0.33)%>%
  head(10)%>%
  knitr::kable()
```

...

## Thống kê mô tả

...

```{r,echo = FALSE, message = FALSE,warning=FALSE}
df_mod %>% 
  group_by(Method, Timepoint) %>% 
  summarize(n = n(),
            median = median(LH),
            mean = mean(LH),
            p5 = quantile(LH, 0.05),
            p95 = quantile(LH, 0.95))%>% 
  knitr::kable(digits = 3)
```

...

```{r,message = FALSE,warning=FALSE}
ggplot()+
  geom_density_ridges(data = df,
                      aes(y = Timepoint, 
                          x = LH, 
                          fill = Method),
                      scale = 1,
                      alpha = 0.3)+
  geom_path(data = df%>%
              filter(Method == 'PPOS'),
            aes(y = Timepoint, 
                x = LH, 
                group = ID),
            color = '#eb176c',
            alpha = 0.3)+
  geom_path(data = df%>%
              filter(Method != 'PPOS'),
            aes(y = Timepoint, 
                x = LH, 
                group = ID),
            color = '#1796eb',
            alpha = 0.3)+
  scale_fill_manual(values = c('#1796eb','#eb176c'))+
  coord_flip()+
  theme_bw(10)
```

...

## Phân tích bài toán 

...

## Giới thiệu về mô hình GEE

...

## Dựng mô hình GEE

...

```{r}
gee1 <- geeglm(formula = LH ~ Method * Timepoint, 
               id = ID,                                   
               data = df_mod, 
               family = Gamma(link = "log"),
               corstr = "exchangeable")

res = data.frame(Str = gee1$corstr,
                 Residual = mean(gee1$residuals))

cor_sts = c("independence", "ar1")

for(j in cor_sts){
  
  mod = geeglm(formula = LH ~ Method * Timepoint, 
               id = ID,                                   
               data = df_mod, 
               family = Gamma(link = "log"),
               corstr = j)
  
  t_res = data.frame(Str = mod$corstr,
                 Residual = mean(mod$residuals))
  
  res = rbind(res, t_res)
}

res
```

...

## Diễn giải kết quả mô hình GEE

...

```{r}
tidy(gee1)%>%
  knitr::kable(digits = 3)
```

...

```{r}
res_0 = avg_comparisons(gee1,
                variables = list(Timepoint = "sequential"))

res_0%>%
  mutate(adj_p = p.adjust(p.value, 
                          method = "BH"))%>%
  mutate(contrast = c("D6 vs D1",
                      "D10 vs D6",
                      "TD vs D10"))%>%
  dplyr::select(-c(1,2,6,7))%>%
  knitr::kable(digits = 3)
```

...

```{r}
res_1 = avg_comparisons(gee1,
                variables = list(Timepoint = "sequential"),
                by = "Method",
                newdata = datagrid(Method = c("GnRHa","PPOS"), 
                     grid_type = 'counterfactual'))

res_1%>%filter(Method == "PPOS")%>%
  mutate(adj_p = p.adjust(p.value, method = "BH"))%>%
  dplyr::select(-c(1,2,7,8,11:13))%>%
  mutate(contrast = c("D6 vs D1",
                      "D10 vs D6",
                      "TD vs D10"))%>%
  knitr::kable(digits = 3)

res_1%>%filter(Method != "PPOS")%>%
  mutate(adj_p = p.adjust(p.value, method = "BH"))%>%
  dplyr::select(-c(1,2,7,8,11:13))%>%
  mutate(contrast = c("D6 vs D1",
                      "D10 vs D6",
                      "TD vs D10"))%>%
  knitr::kable(digits = 3)
```

...

```{r}
res_2 = avg_comparisons(gee1,
                variables = "Method",
                by = "Timepoint")

res_2%>%
  mutate(adj_p = p.adjust(p.value, method = "BH"))%>%
  dplyr::select(-c(1,2,7,8,11:13))%>%
  mutate(contrast = c("PPOS - GnRHa"))%>%
  knitr::kable(digits = 3)
```

...

```{r}
preds = predictions(model = gee1)

preds%>%
  group_by(Method,Timepoint)%>%
  summarize_at('estimate', median) -> m1_sum

preds%>%ggplot()+
  geom_density_ridges(aes(x = LH, 
                          y = Timepoint,
                          fill = Method),
                      scale = 0.8,
                      alpha = 0.5,
                      show.legend = T)+
  geom_errorbar(aes(y=Timepoint, 
                    xmin=conf.low, 
                    xmax=conf.high,
                    color = Method),
                width=0.2,
                linewidth = 1)+
  geom_path(data = m1_sum,
            aes(y=Timepoint, 
                x=estimate,
                group = Method,
                col = Method))+
  geom_point(aes(y=Timepoint, 
                 x=estimate,
                 col = Method), 
             size=3)+
  scale_x_continuous(limits = c(0,8), 
                     breaks = c(seq(0,8,1)))+
  labs(x="LH level", 
       y = "Time point") + 
  coord_flip()+
  scale_fill_manual(values = c('#1796eb','#eb176c'))+
  scale_color_manual(values = c('blue4','red4'))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, 
                                   vjust = 1, 
                                   hjust=1)) +
  theme(axis.text = element_text(size = 10, 
                                 color = "black"),
        axis.title = element_text(size = 10, 
                                  color = "black"))
```

## Diễn đạt kết quả của phân tích:

...

## Thông điệp rút gọn làm hành trang

...
