# Ứng dụng sơ đồ mạng định hướng không tuần hoàn (DAG)

## Đặt vấn đề

...

## Bối cảnh của thí nghiệm

...

## Kế hoạch phân tích

...

```{r,message = FALSE,warning=FALSE}
library(tidyverse)
library(ggridges)

library(broom)
library(dagitty)
library(ggdag)

library(marginaleffects)

library(patchwork)
```

...

```{r,message = FALSE,warning=FALSE}
df <- read.csv('Letrozole_PCOS.csv', 
               sep = ';', dec= ',', 
               fileEncoding = 'UTF-8-BOM')%>%na.omit()

df$Method = factor(df$Method)
df$Inserm = factor(df$Inserm)
df$Type = factor(df$Type)
df$COS = factor(df$COS)
df$Transf = factor(df$Transf)
df$Stage = factor(df$Stage)


df%>%head()%>%dplyr::select(c(1,16,2:7))%>%
  knitr::kable(digits = 2)

df%>%head()%>%dplyr::select(c(1,16,8:15))%>%
  knitr::kable(digits = 2)
```

## Mô tả đơn giản

...

```{r,message = FALSE,warning=FALSE}
df%>%group_by(Method)%>%
  summarize(n = n(),
            LiveBirth = sum(LBirth==1),
            Failure = sum(LBirth==0),
            p1 = mean(LBirth),
            p0 = 1- p1,
            )%>%knitr::kable()
```

...

## Sơ đồ nhân quả và mô hình DAG

...

```{r,message = FALSE,warning=FALSE}
coord_dag <- list(x = c(Birth = 9,
                        FSH = 1.5,
                        LH = 3,
                        Inserm = 1,
                        MII = 3.5,
                        Age = 4,
                        BMI = 7,
                        Fert = 3.5,
                        Embryo = 5,
                        EndThck = 7,
                        Preg = 7,
                        Letroz = 6.5,
                        Infdt = 5.5,
                        Stim = 1,
                        Ooc = 2.5),
                  y = c(Birth = 2,
                        FSH = 7.5,
                        LH = 7.5,
                        Inserm = 2,
                        MII = 2.5,
                        Age = 9,
                        BMI = 8.5,
                        Fert = 1,
                        Embryo = 2,
                        EndThck = 4,
                        Preg = 2,
                        Letroz = 6,
                        Infdt = 8,
                        Stim = 5.5,
                        Ooc = 4
                        )
                        )

dag <- dagify(
      Birth ~ BMI + Preg + Age,
      Preg ~ EndThck  + Letroz + Embryo + Age,
      EndThck ~ Age + Letroz + BMI,
      Embryo ~ LH + Fert + Stim,
      Fert ~ MII + Inserm + LH,
      MII ~ Ooc + Stim + Letroz,
      Ooc ~ Letroz + FSH + LH + Stim + Age,
      Letroz ~ Infdt + Age + BMI + Stim,
      FSH ~ Age + BMI,
      LH ~ Age + BMI,
      BMI ~ Age,
      coords = coord_dag,
      exposure = "Letroz",
      outcome = "Birth"
      )

dag%>%tidy_dagitty()%>%
  mutate(colors = recode(factor(name),
                         Birth = 1,
                        FSH = 2,
                        LH = 2,
                        Inserm = 5,
                        MII = 3,
                        Age = 6,
                        BMI = 6,
                        Fert = 3,
                        Embryo = 3,
                        EndThck = 4,
                        Preg = 3,
                        Letroz = 5,
                        Infdt = 6,
                        Stim = 5,
                        Ooc = 4
                         ))%>%
  ggdag::ggdag(edge_type = "diagonal") + 
  geom_dag_point(aes(colour = factor(colors)),
                 show.legend = F) +
  geom_dag_text(text_size = 3, 
                color = "black") +
  scale_color_brewer(palette = "Spectral")+
  theme_dag()
```

## Xác định tập hợp biến cần hiệu chỉnh

...

```{r}
paths(dag)$paths[c(1:10)]
```

...

```{r,message = FALSE,warning=FALSE}
ggdag_adjustment_set(dag, 
                     shadow = T,
                     node_size = 12, 
                     exposure = "Letroz",
                     outcome = "Birth",
                     text_size = 3) + 
  theme_dag()+
  scale_color_manual(values = c("#f54278","#cbcfd1"))+
  theme(legend.position = "bottom")

adjustmentSets(dag, "Letroz","Birth")
```

## Ước lượng bằng mô hình hồi quy logistic

...

**Trường hợp hiệu chỉnh máy móc và quá đáng**

...

```{r}
fit1 <- glm(LBirth ~ Method + Age + BMI + COS + 
              FSH + LH + nOOC + Inserm + 
              nEmbryo + Stage + Transf + Thickness,
            data = df,
           family = binomial)

rd = avg_comparisons(fit1, 
                     variables = "Method",
                     newdata = df)

rd%>%
  knitr::kable(digits = 3)

or = avg_comparisons(
  fit1,
  variables = "Method",
  transform_pre = "lnoravg",
  transform_post = "exp")

or %>%
  mutate(contrast = "OR")%>%
  knitr::kable(digits = 3)
```

...

**Khi không hiệu chỉnh gì cả**

...

```{r}
fit2 <- glm(LBirth ~ Method,
            data = df,
           family = binomial)

rd = avg_comparisons(fit2, 
                     variables = "Method",
                     newdata = df)

rd%>%
  knitr::kable(digits = 3)

or = avg_comparisons(
  fit2,
  variables = "Method",
  transform_pre = "lnoravg",
  transform_post = "exp")

or %>%
  mutate(contrast = "OR")%>%
  knitr::kable(digits = 3)
```

...

**Khi hiệu chỉnh vừa đủ và chính xác**

...

```{r,message = FALSE,warning=FALSE}
# m.data <- match.data(m.out1)
fit3 <- glm(LBirth ~ Method + Age + COS + BMI,
           data = df,
           family = binomial)

rd%>%
  knitr::kable(digits = 3)
  
or = avg_comparisons(
  fit3,
  variables = "Method",
  transform_pre = "lnoravg",
  transform_post = "exp")

or %>%
  mutate(contrast = "OR")%>%
  knitr::kable(digits = 3)
```

...

## Thông điệp rút gọn làm hành trang:

...
