--- 
title: "Phân tích dữ liệu cho nghiên cứu hỗ trợ sinh sản bằng ngôn ngữ R"
author:
  - Chủ biên;
  - BS. Lê Ngọc Khả Nhi, Ths.BS Thân Trọng Thạch, PGS.TS Lê Hoàng.
  - Đồng tác giả; 
  - BS Dương Thị Ngọc Châu, BS. Nguyễn Hà Ngọc Thiên Thanh
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
geometry: paperheight=10.4331in,paperwidth=7.48031in,margin=0.95in

bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Giáo trình thống kê chuyên dụng cho nghiên cứu hỗ trợ sinh sản"
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = F, 
                      warning = F,
                      message = F,
                      background = "#faf8eb")

options(knitr.table.format = "latex")
```

# Lời giới thiệu

**Biên soạn:** Lê Ngọc Khả Nhi, Thân Trọng Thạch

## Giới thiệu về nghiên cứu hỗ trợ sinh sản

### Đặt vấn đề

Vô sinh là một vấn đề sức khỏe quan trọng với ước tính tỉ lệ gặp phải trên khoảng 17,5% dân số trên toàn thế giới [@th01]. Vấn đề này không chỉ phổ biến tại các quốc gia phát triển cao do dân số già hóa và ở những vùng đô thị - nơi tuổi người phụ nữ sinh con đầu ngày càng cao, mà còn được ghi nhận phần lớn ở các nước đang phát triển, trong đó có Việt Nam [@th02].

Cùng với sự gia tăng tỉ lệ vô sinh, sự phát triển nhanh của Y học sinh sản và nghiên cứu khoa học về hỗ trợ sinh sản (HTSS) đã đóng góp rất lớn cho sự phát triển của các kỹ thuật trong điều trị và chăm sóc các cặp đôi vô sinh trên toàn thế giới. Em bé IVF đầu tiên trên thế giới ra đời năm 1978, đến nay ước tính đã có hơn 8 triệu trẻ ra đời từ thụ tinh ống nghiệm (IVF) [@th03]. 

IVF đã làm thay đổi quan điểm của nhân loại về sinh sản. Đi cùng với sự công nhận trên toàn thế giới và sự phổ biến về dịch vụ HTSS là nhu cầu cần có những nghiên cứu chất lượng đề phát triển những kỹ thuật trong HTSS tại các nước đang phát triển. Mặc dù số lượng tạp chí và bài báo về lĩnh vực y học sinh sản tăng mạnh trong những năm gần đây, tại một số nước và khu vực, việc nghiên cứu khoa học (NCKH) vẫn chưa thật tương xứng với những thành tựu đạt được trong HTSS.

Với tiềm năng thị trường và nguồn nhân lực, Việt Nam có cơ hội rất lớn để phát triển  IVF thành ngành mũi nhọn về công nghệ Y-sinh học. Lĩnh vực HTSS tại nước ta có nhiều thuận lợi để thực hiện nghiên cứu khoa học như nguồn dữ liệu lớn, số lượng bệnh nhân điều trị đông, tuy nhiên số lượng công trình khoa học hiện tại của nước ta chưa nhiều. Việc thực hiện nghiên cứu khoa học về HTSS tại Việt Nam đang gặp phải những khó khăn gì? Trong phần này, tác giả sẽ trình bày tổng quan về lịch sử nghiên cứu khoa học trong HTSS và tầm quan trọng của khoa học thực nghiệm trong quá trình phát triển của HTSS. 

### Lịch sử nghiên cứu về IVF

**Những ngày đầu của IVF**

Từ những năm 1930, việc nghiên cứu hiện tượng thụ tinh giữa noãn và động vật bậc cao trong môi trường bên ngoài cơ thể nhận được sự chú ý [@th07]. Những ý tưởng về trưởng thành trứng của Edward bắt đầu từ những năm 1950 với mục tiêu tìm hiểu nguồn gốc của việc trưởng thành trứng để có thể tránh được các bất thường nhiễm sắc thể bao gồm hội chứng Turner, Klinefelter hay Down. Năm 1959, Chang lần đầu tiên thực hiện thành công thụ tinh giữa tinh trùng và noãn động vật có vú (thỏ) trong môi trường phòng thí nghiệm [@th08]. Đây được xem là thành tựu quan trọng nhất trong lịch sử phát triển IVF vì nó chứng mình noãn và tinh trùng của động vật có thể thụ tinh được bên ngoài cơ thể. Từ sau thí nghiệm này, IVF được nghiên cứu trên nhiều loài động vật khác nhau, kể cả ở người. 

Năm 1962, Edward nhận thấy rằng có thể kích thích sự trưởng thành của trứng bằng cách sử dụng hormone cho chuột cái trưởng thành, điều này tạo tiền đề cho việc kích thích rụng trứng ở người sau này [@th09]. Năm 1966, Edward cùng một nhóm các nhà khoa học Mỹ công bố trường hợp đầu tiên lấy được noãn người nhờ phẫu thuật nội soi [@th10]. Sau đó, Edward dành 6 năm để thực hiện trưởng thành trong ống nghiệm trứng của nhiều loài khác nhau, bao gồm cả ở người. Ở bước này, ông mất khá nhiều thời gian vì ở thời điểm bấy giờ, không ai biết sau bao lâu sau đỉnh LH thì trứng rụng và tiếp tục chu kì giảm phân. Trên thực tế, khoảng thời gian này ở người (36 giờ) dài hơn nhiều so với khoảng thời gian 12 giờ được nghiên cứu trên chuột trước đó. Sau đó, trong vòng 2-3 năm, Edward tập trung thực hiện xét nghiệm di truyền tiền làm tổ (PGT) trên phôi chuột, tạo tiền đề cho kỹ thuật PGT trên phôi người 20 năm sau đó. Năm 1971, Steptoe và Edwards ở lần đầu tiên báo cáo nuôi cấy được phôi nang người (blastocyst) trong ống nghiệm và chuyển phôi vào buồng tử cung [@th11]. Tuy nhiên thời gian này, các phác đồ để chuẩn bị nội mạc chưa được nghiên cứu một cách kỹ lưỡng và các nhà khoa học đã mắc nhiều sai lầm trong việc sử dụng nội tiết tố để chuẩn bị nội mạc tử cung. Đến năm 1976, sau nhiều trường hợp thất bại, Steptoe và Edwards công bố trường hợp thai IVF đầu tiên trên thế giới tại bệnh viện Oldham, Anh, nhưng đáng tiếc đây là một trường hợp thai ngoài tử cung [@th12]. 

Năm 1978, Louise Brown, em bé IVF đầu tiên ra đời, tạo nên thành công đầu tiên cho sự phát triển IVF trên người [@th03]. Em bé Louise Brown được sinh ra từ người mẹ được chẩn đoán vô sinh do tổn thương hai vòi trứng đã được điều trị bằng phẫu thuật nhưng không thành công. Trong thực tế, bác sĩ Steptoe và tiến sĩ Edwards đã thất bại hàng trăm lần để có được thành công vang dội này. Tuy nhiên, trong giai đoạn này, các nhà khoa học tiên phong như bác sĩ Steptoe và tiến sĩ Edwards đã hứng phải chỉ trích và phản ứng kịch liệt không chỉ từ dư luận, tôn giáo mà còn từ nhiều nhà khoa học đương thời. Trong thời gian dài nhiều năm, các nhà khoa học làm trong lĩnh vực IVF đã âm thầm lặng lẽ làm việc và nghiên cứu. Sau 32 năm kể từ khi IVF ở người thành công và em bé từ IVF đầu tiên chào đời, năm 2010 sự đóng góp của tiến sĩ R.G. Edwards đã được các nhà khoa học trên thế giới công nhận là một cột mốc lớn trong sự phát triển của nền y học hiện đại và ông được trao giải thưởng Nobel Y học cho thành tựu này [@th13].

Trong những năm 80, kỹ thuật IVF đã được phát triển rất mạnh và lần lượt được báo cáo thành công tại nhiều nước ở nhiều khu vực trên thế giới. Năm 1981, em bé IVF đầu tiên ở Mỹ ra đời, đây cũng là trường hợp IVF đầu tiên sử dụng gonadotropin để kích thích buồng trứng. Các nước châu Âu cũng đồng loạt triển khai IVF trong những năm đầu thập niên 80 [@th14]. Tại châu Á, Singapore là nơi đầu tiên thực hiện thành công IVF vào năm 1983. Sau đó, IVF cũng được thực hiện thành công tại Nhật Bản, Trung  Quốc, Thái Lan, Malaysia, Indonesia và Philippines trong suốt những năm của thập niên 80. 

Tại Việt Nam, IVF đã mất hơn 10 năm để chuẩn bị do hạn chế về cơ sở vật chất, kỹ thuật, nhân lực chuyên môn. Ngày 19/8/1997, bộ trưởng Bộ Y Tế đã ký quyết định cho phép bệnh viện Từ Dũ là đơn vị đầu tiên tại Việt Nam được thực hiện những ca IVF đầu tiên, đứng đầu nhóm nghiên cứu là bác sĩ Nguyễn Thị Ngọc Phượng. Nhận được sự hỗ trợ và hợp tác của các chuyên gia người Pháp, vào tháng 8/1997 các trường hợp IVF đầu tiên tại Việt Nam đã được thực hiện. Ngày 30/4/1998, đánh dấu mốc quan trọng cho IVF Việt Nam, khi 3 em bé IVF đầu tiên của Việt Nam được chào đời. Từ năm 1997-2007, trong vòng 10 năm, IVF ở Việt Nam phát triển rất nhanh, thực hiện được nhiều kỹ thuật chuyên sâu về IVF. Đến năm 2007, Việt Nam đã thực hiện được hầu hết các kỹ thuật liên quan đến IVF. Từ năm 2007 trở đi, IVF Việt Nam có những chuyển biến mạnh mẽ về chất lượng, nâng lên một tầm cao mới. Tỷ lệ thành công được cải thiện một cách đáng kể và xứng ngang tầm với các trung tâm trên thế giới.

**Quá trình phát triển và hoàn thiện về kỹ thuật**

Đến nay, IVF đã có những sự phát triển vượt bậc. Từ kỹ thuật chọc hút trứng được thực hiện dưới gây tê tại chỗ, dưới sự hướng dẫn của siêu âm qua ngã âm đạo, đến phương pháp nuôi cấy phôi, nuôi cấy thành công phôi nang, cũng như tiêu chuẩn lựa chọn trứng và kỹ thuật thủy tinh hóa giúp trữ đông phôi, giảm số lượng phôi mỗi lần chuyển và tránh được những vấn đề liên quan khi mang đa thai. Ở những chu kỳ IVF đầu tiên được thực hiện, người ta chỉ thực hiện chọc hút lấy noãn qua nội soi trên những buồng trứng phát triển tự nhiên, nên thường chỉ lấy được một noãn từ một phụ nữ và do đó, tỉ lệ thành công thường rất thấp. Khi việc sử dụng nội tiết tố để kích thích buồng trứng ngày càng phổ biến, người ta có thể lấy được trung bình khoảng 10 noãn để thực hiện IVF. Điều này giúp tăng số lượng phôi có được và có thể lựa chọn được phôi có chất lượng tốt để chuyển vào buồng tử cung, làm gia tăng đáng kể tỉ lệ thành công của IVF. 

Từ năm 1983, siêu âm đầu dò âm đạo được đưa vào ứng dụng trong phụ khoa. Kỹ thuật chọc hút noãn qua ngã âm đạo dưới hướng dẫn của siêu âm đầu dò âm đạo được áp dụng lần đầu tiên và sau đó thay thế hoàn toàn việc chọc hút noãn qua nội soi tốn kém, xâm lấn và kém hiệu quả. Thành tựu này làm thay đổi đáng kể bộ mặt của kỹ thuật IVF, biến IVF thành một kỹ thuật đơn giản, ít xâm lấn, có thể thực hiện ở các cơ sở y tế nhỏ [@th15].

Cũng vào năm 1983, nhóm nghiên cứu của Alan Trouson tại Úc công bố trường hợp em bé đầu tiên sinh ra từ phôi trữ đông [@th16]. Sau đó, vào năm 1986, Chen cùng cộng sự báo cáo trường hợp có thai từ noãn người đông lạnh và rã đông tại Úc [@th17]. Tuy nhiên, trong một thời gian dài sau đó, các phác đồ trữ lạnh noãn cho hiệu quả kém và tỉ lệ thành công được báo cáo rất thấp. Trong thời gian gần đây, nhờ sự phát triển của kỹ thuật thủy tinh hóa, đông lạnh noãn bắt đầu được đánh giá là một kỹ thuật hiệu quả. Hiện nay, kết quả đông lạnh noãn đã đạt kết quả tỉ lệ sống tương đương với đông lạnh phôi và chất lượng noãn sau rã đông tương đương với noãn tươi.

Năm 1984, kỹ thuật chuyển giao tử vào vòi trứng (GIFT – Gamete intrafallopian tube transfer) do bác sĩ Asch khởi xướng được báo cáo thành công tại Mỹ. Khi thực hiện GIFT, noãn và tinh trùng được lấy ra ngoài cơ thể, xử lí và sau đó tinh trùng và noãn chỉ được tiếp xúc với nhau khi được bơm vào vòi trứng bằng nội soi ổ bụng. Đây là một kỹ thuật xâm lấn và đòi hỏi người bệnh phải có ít nhất một vòi trứng bình thường. Kỹ thuật này phát triển mạnh mẽ trong những năm sau đó tại Mỹ vì các thời điểm bấy giờ các phác đồ nuôi cấy phôi trong điều kiện nhân tạo chưa hoàn thiện và một số quan điểm tôn giáo không chấp nhận IVF [@th18]. Một kỹ thuật khác tương tự là chuyển hợp tử vào vòi trứng (ZIFT - Zygote intrafallopian tube transfer) cũng được phát triển sau đó. Trong kỹ thuật này hợp tử được hình thành ở môi trường bên ngoài cơ thể, sau đó được bơm vào vòi trứng qua nội soi ổ bụng. Đến cuối thập kỷ 90, GIFT và ZIFT ngày càng bị thu hẹp chỉ định do sự phát triển của kỹ thuật nuôi cấy phôi trong phòng thí nghiệm được cải thiện đáng kể, đồng thời IVF ngày càng trở nên phổ biến và chấp nhận rộng rãi.

Em bé đầu tiên ra đời từ một người phụ nữ không còn buồng trứng và thực hiện xin noãn vào năm 1984 [@th19]. Đây là lần đầu tiên trong lịch sử một người phụ nữ có thể có con với noãn của một người phụ nữ khác. Trong một bước đột phá của IVF, năm 1997, một trường hợp người phụ nữ 63 tuổi có thai với kỹ thuật xin noãn – IVF được báo cáo. Điều này chứng tỏ rằng chức năng mang thai của tử cung nếu được bổ sung đủ nội tiết thì có thế duy trì khá lâu sau mãn kinh. Tuy nhiên, đa số các nước đều giới hạn độ tuổi xin noãn thường dao động từ 45 – 55 tuổi. 

Trong thời gian đầu, IVF được chỉ định chủ yếu cho vô sinh nữ. Sau đó, IVF được áp dụng cho các trường hợp vô sinh nam, trong đó kỹ thuật vi thao tác (micromanipulation) được nghiên cứu để hỗ trợ cho việc thụ tinh giữa noãn và tinh trùng trong trường hợp thiểu năng tinh trùng. Trong kỹ thuật vi thao tác, kim cực nhỏ bằng thủy tinh được dùng để thao tác trên noãn và tinh trùng dưới kính hiển vi đảo ngược. Năm 1988, trường hợp tiêm trùng vào dưới màng trong suốt (SUZI - Subzonal insemination) được báo cáo thành công lần đầu tiên tại Singapore [@th20]. Trong kỹ thuật này, một vài tinh trùng được tiêm trực tiếp qua màng trong suốt (zona pellucida) vào khoang quanh noãn (perivitelline space) để hỗ trợ cho tinh trùng thụ tinh với noãn. Cũng vào năm 1988, kỹ thuật đục thủng màng trong suốt (PZD) được giới thiệu lần đầu bởi Cohen. Trong kỹ thuật này, tác giả đã sử dụng vi thao tác đục thủng màng trong suốt, sau đó cấy tinh trùng vào noãn. Tuy nhiên, cả SUZI và PZD đều không đạt được hiệu quả cao do tỉ lệ thụ tinh của noãn và tinh trùng không tăng đáng kể nhưng tỉ lệ thụ tinh đa tinh trùng (polyspermia) lại tăng cao [@th21]. 

Thai kỳ đầu tiên thực hiện PGT được báo cáo vào năm 1990, và chỉ sau 10-15 năm sau đó, PGT được thực hiện thường quy trong IVF, đặc biệt là tại Mỹ. Hiện tại, có 3 kỹ thuật tiếp cận sinh thiết phôi thực hiện PGT được áp dụng: sau thụ tinh, sinh thiết phôi ngày 5 hoặc ít phổ biến hơn là sinh thiết phôi ngày 2,3 đang phân chia; trước thụ tinh, sinh thiết thể cực để xác định bất thường di truyền ở trứng, nhưng hiện tại ít được sử dụng. Mỗi cách lấy mẫu sinh thiết có ưu và nhược điểm riêng về độ nhạy và tính tin cậy. Kỹ thuật lấy mẫu phụ thuộc vào mục đích của sử dụng test chẩn đoán bao gồm: (1) chẩn đoán giới tính phôi thai để tránh các bệnh lý di truyền theo nhiễm sắc thể giới tính; (2) phát hiện khiếm khuyết đơn gene ở phôi thai; (3) bất thường nhiễm sắc thể như lệch bội, đa bội và chuyển đoạn phức tạp có thể phát hiện qua xét nghiệm di truyền tiền làm tổ dành cho lệch bội (PGT-A). 

Hiện nay, tại một số trung tâm, việc thực hiện PGT-A ở tất cả phụ nữ, phụ nữ lớn tuổi, hoặc phụ nữ có sảy thai lặp lại nhiều lần trước đó dần trở thành thường quy. Tuy nhiên, các thử nghiệm lâm sàng ngẫu nhiên có đối chứng không cung cấp được bằng chứng rõ ràng về giá trị của việc sử dụng rộng rãi hay có chọn lọc PGT-A, đặc biệt khi tình trạng thể khảm được phát hiện ngày càng nhiều trong sinh thiết phôi nang. Kỹ thuật được sử dụng cho chẩn đoán di truyền là lấy mẫu sinh thiết nên kỹ thuật khác nhau tùy vào mục đích của xét nghiệm được thực hiện. Trước đây, có 2 kỹ thuật được thực hiện: (i) nhuộm huỳnh quang tại chỗ phát hiện bất thường karyotypes, bất thường cấu trúc nhiễm sắc thể hay giới tính phôi thai và (ii) phản ứng chuỗi polyme hóa (PCR) giúp phát hiện bệnh lý đơn gene. Gần đây, đã có nhiều sự phát triển vượt bậc trong công nghệ khuếch đại toàn bộ gene (WGA), array CGH và đa hình nucleotide đơn dựa trên array (SNP). Hiện nay, công nghệ giải trình tự gene thế hệ mới (NGS) cho phép giải trình tự tự động vì vậy chi phí phấp hơn so với kỹ thuật array CGH14. 

Năm 1992, kỹ thuật tiêm tinh trùng vào bào tương noãn (ICSI) được giới thiệu và tạo nên cuộc cách mạng về điều trị vô sinh ở nam. Trong kỹ này, một tinh trùng được tiêm trực tiếp vào bào tương noãn để hỗ trợ sự thụ tinh. Các thử nghiệm đầu tiên đều cho thấy rằng sau khi tiêm tinh trùng vào noãn, tế bào noãn vẫn có thể tự hồi phục, sự thụ tinh diễn ra và phôi sau đó phát triển khá tốt [@th22]. Tỷ lệ có thai lâm sàng của kỹ thuật ICSI cao hơn so với IVF cổ điển, mặc dù chất lượng và số lượng tinh trùng kém. Nếu như trong điều kiện sinh lý tự nhiên, người nam cần sản xuất hàng triệu tinh trùng để có thể thụ tinh được một noãn trong vòi trứng, thì với kỹ thuật ICSI, sự thụ tinh có thể diễn ra giữa duy nhất một tinh trùng và một noãn. Hiện nay, tại một số trung tâm lớn, ICSI còn được áp dụng thay thế hoàn toàn kỹ thuật IVF cổ điển ngay cả đối với trường hợp không liên quan đến vô sinh nam [@th23].

Trước khi ICSI ra đời, những trường hợp nam giới không có tinh trùng do bế tắc (Obstructive Azoospermia) được điều trị bằng cách hút tinh trùng ở trước vị trí tắc để bơm tinh trùng vào buồng tử cung (IUI) hoặc thực hiện IVF. Năm 1994, các trường hợp hút tinh trùng từ mào tinh qua vi phẫu và tiêm tinh trùng vào bào tương noãn (MESA – ICSI) đầu tiên được thực hiện. Sau đó, năm 1995, kỹ thuật chọc hút tinh trùng từ mào tinh xuyên da và tiêm tinh trùng vào bào tương noãn (PESA – ICSI) được giới thiệu giúp đơn giản hóa việc điều trị không có tinh trùng do bế tắc. Trong kỹ thuật PESA, không cần phải mở bao tinh hoàn mà chỉ cần chọc kim sinh thiết vào mào tinh và hút tinh trùng, và kỹ thuật này có thể thực hiện tại phòng khám [@th24]. 

Tiếp nối những thành công trên, kỹ thuật phân lập tinh trùng từ tinh hoàn ở những trường hợp giảm sinh tinh tại tinh hoàn và tiêm tinh trùng vào bào tương noãn (TESE – ICSI) lần đầu giới thiệu vào năm 1995. Ở những trường hợp này, tinh hoàn giảm sản xuất tinh trùng nghiêm trọng, đến mức có thể không tìm thấy tinh trùng trong tinh dịch; kích thước tinh hoàn nhỏ hoặc chỉ còn một bên tinh hoàn hoạt động; chức năng sản xuất nội tiết tố của tinh hoàn giảm. Tỉ lệ thành công của TESE – ICSI cũng đạt gần tương đương với tỉ lệ thành công chung của IVF [@th25].

Năm 1991, Cha cùng cộng sự đã báo cáo trường hợp có thai đầu tiên với noãn trưởng thành trong ống nghiệm (IVM). Trong kỹ thuật này, noãn non được chọc hút từ những nang nhỏ của buồng trứng vào giai đoạn sớm của pha nang noãn. Những nang noãn này sau đó được nuôi cấy trưởng thành trong môi trường bên ngoài cơ thể. Một tỉ lệ lớn noãn có thể trưởng thành và thụ tinh bằng phương pháp ICSI. IVM đã mở ra một hướng đi mới cho TTTO, trong đó không cần thực hiện kích thích buồng trứng bằng nội tiết tố, từ đó có thể giảm chỉ phí điều trị và các biến chứng có thể gặp của kích thích buồng trứng. Kỹ thuật IVM thích hợp với các bệnh nhân có hội chứng buồng trứng đa nang. Và gần đây, IVM được nghiên cứu và áp dụng cho hầu hết các chỉ định thường quy của IVF [@th26].

### Xu hướng nghiên cứu IVF

Bên cạnh sự thành công của HTSS hiện đại là những hạn chế như tỷ lệ chu kỳ thất bại cao, việc sử dụng IVF rộng rãi như điều trị theo kinh nghiệm, thiếu những lựa chọn quản lý trong những trường hợp giảm trữ lượng buồng trứng liên quan đến tuổi, những nguy cơ y khoa liên quan đến việc kích thích buồng trứng và chọc hút noãn, gánh nặng tâm lý liên quan đến việc điều trị hiếm muộn, gánh nặng về tài chính đối với người bệnh, tỉ lệ đa thai cao, và thiếu những hiểu biết đúng về điều trị IVF. Ngày càng có nhiều kỹ thuật IVF ra đời nhằm cải thiện kết cục điều trị. 

Một điều đáng lưu ý, đó là số lượng phát minh mới trong điều trị IVF chưa hẳn đáp ứng tức thì những mong ước thực tiễn như giúp các cặp đôi dễ dàng có con hơn, ít gánh nặng chi phí hơn và ít nguy cơ cho bố mẹ và em bé hơn. Thực tế gần đây cho thấy rất ít phát hiện mới trong lĩnh vực y học sinh sản được ứng dụng vào thực hành lâm sàng sau khi trải qua kiểm định nghiêm ngặt [@th04]. Câu hỏi đặt ra rằng các thử nghiệm lâm sàng ngẫu nhiên có kiểm soát (RCT) đã giúp ích cho sự phát triển của YHSS như thế nào ? RCT được xem như thiết kế nghiên cứu tối ưu để đánh giá chính xác hiệu quả của một can thiệp mới. Khi kết cục là biến nhị phân (ví dụ trong YHSS thường là “có” hoặc “không có” mang thai), cần có kích thước cỡ mẫu lớn để tìm ra những ảnh hưởng đến kết cục lâm sàng với đủ độ tin cậy. 

Trong những tổng quan hệ thống (systematic review) và phân tích tổng hợp (meta analysis) dựa trên RCT trong thời gian gần đây về lĩnh vực YHSS, người ta nhận thấy rằng nhiều nghiên cứu RCT không đạt được mục tiêu này [@th05]. Trong thư viện Cochrane, không một nghiên cứu RCT đơn độc nào đủ mạnh và chỉ có 2% phân tích tổng hợp đủ lớn để phát hiện sự khác biệt 5% về tỉ lệ sinh sống khi thực hiện một can thiệp nhất định [@th05]. Hơn nữa, các tác giả sử dụng nhiều phương thức để đánh giá và định nghĩa kết cục, đây là một điều góp phần cho việc khó khăn trong so sánh giữa các RCT. Mặc dù đã có nhiều lời kêu gọi thực hiện các nghiên cứu RCT trong lĩnh vực HTSS, tuy nhiên số lượng nghiên cứu RCT đến hiện tại vẫn khá hạn chế [@th06].

Tại sao việc thực hiện nghiên cứu trong lĩnh vực HTSS lại tiến triển chậm như vậy? Tuy RCT là thiết kế hiệu quả, nhưng cần có sự nỗ lực trong hợp tác giữa các trung tâm để có được những thử nghiệm đủ lớn. Mặc dù sự cạnh tranh là điều cần thiết cho tiến bộ khoa học, nhưng thế giới IVF dường như đang bận rộn với sự cạnh tranh về khía cạnh kinh tế trong việc cung cấp các dịch vụ HTSS hơn là khoa học về sinh sản. HTSS đang chứng kiến quá trình công nghiệp hóa các dịch vụ y tế với tốc độ nhanh chóng và quy mô lớn. Vì vậy mà hoạt động nghiên cứu khoa học mang tính cục bộ chưa xứng tầm với nguồn dữ liệu lớn của lĩnh vực này.

Sự thành công của YHSS hiện nay là nhờ sự khám phá nhiều kỹ thuật mới như sử dụng xét nghiệm miễn dịch phóng xạ để định lượng nồng độ hormone, phác đồ kích thích buồng trứng vào những năm 60 của thế kỷ trước, và kế sau đó là thụ tinh trong ống nghiệm và cho ra đời em bé đầu tiên sinh ra từ TTON vào năm 1978. Để đạt được sự phát triển vượt trội như vậy, y học lâm sàng cần những nghiên cứu có chất lượng cao và những bài báo được trích dẫn rộng rãi bởi những nhà khoa học khác. Những tạp chí về YHSS có yếu tố ảnh hưởng (impact factor) ngày càng tăng [@th27]. 

Năm 2015, Aleixandre-Benavent cùng cộng sự đã thực hiện nghiên cứu nhằm mục đích khảo sát xu hướng trong nghiên cứu lâm sàng lĩnh vực hỗ trợ sinh sản. Những bài báo được chọn lựa là những bài thuộc về lĩnh vực sinh học sinh sản  được báo cáo trong “Journal Citation Report” trong giai đoạn 2003 – 2012. Kết quả ghi nhận có 90 tác giả với hơn 1000 lượt trích dẫn với 4.010 bài báo (3.583 tạp chí và 427 bài đánh giá). Số lượng bài báo về YHSS được đăng trên những tạp chí có chỉ số ảnh hưởng (impact factor) cao nhất là 3.662 bài báo, trong đó “Human  Reproduction” là tạp chí có số lượng bài nhiều nhất (n=980), kế đến là “Fertility & Sterility” (n=891). 

Tạp chí đầu tiên không về YHSS đăng bài về lĩnh vực YHSS là “Journal of Clinical Endocrinology and Metabolism” (n=288), và kế tiếp là “British  Journal  of  Obstetrics  and  Gynaecology” (n=77). Số lượng bài báo về lĩnh vực sinh lý sinh sản còn khá hạn chế. Tuy nhiên, yếu tố ảnh hưởng của những tạp chí về YHSS tăng khá nhanh, và hiện tại yếu tố ảnh hưởng đã tương đương với các tạp chí lĩnh vực khoa học khác như nhi khoa, hô hấp, nhãn khoa, sản phụ khoa và lão khoa. Hơn nữa, số lượng bài báo công bố về YHSS tăng nhanh hơn so với các lĩnh vực khoa học khác. Trong đó, Fauser là tác giả có số lượng trích dẫn cao nhất, với số lượng trích dẫn trong lĩnh vực YHSS là 7451, tiếp theo là Azziz (n=6.347), và Devroey (n=6104). Nơi nghiên cứu có số lượng trích dẫn cao nhất là Trung tâm Y khoa Đại học Erasmus (Rotterdam, Hà Lan) (n=9006 trích dẫn), theo sau là Trung tâm Y khoa Đại học Utrecht (Hà Lan) (n=7.108) và Đại học Vrije Brussels (Bỉ) (n=6.846). Nhóm tác giả nhận thấy rằng có đến 22% những tạp chí có lượng trích dẫn cao nhất được đăng trong những tạp chí có lĩnh vực nghiên cứu chính không phải là sinh học sinh sản. 

Những quốc gia có số lượng trích dẫn cao nhất là Hà Lan, Bỉ, Tây Ban Nha, Hoa Kỳ và Anh, và số lượng nghiên cứu đang tăng lên từng ngày. Những từ khóa quan trọng xuất hiện ngày càng nhiều trong những nghiên cứu về YHSS là “kỹ thuật HTSS”, “IVF”, “kết cục thai kỳ” và “sức khỏe trong tương lai của mẹ và bé sau thực hiện IVF”. Như vậy, thông qua phân tích trên đã cung cấp bằng chứng thuyết phục về sự “trưởng thành” của các nghiên cứu khoa học trong lĩnh vực HTSS, số lượng các nghiên cứu có chất lượng cao được đăng trong các tạp chí không thuộc lĩnh vực HTSS và có yếu tố ảnh hưởng cao ngày càng nhiều. Sự phát triển nhanh về các kỹ thuật điều trị và ra mắt nhiều mô hình điều trị mới đòi hỏi sự giám sát chặt chẽ của quốc gia và quốc tế về tính hiệu quả và an toàn cho cả bố mẹ và em bé được điều trị [@th28].

Đứng trước sự phát triển mạnh mẽ của trí tuệ nhân tạo, lĩnh vực HTSS cũng không nằm ngoài xu hướng đó. Machine learning là một nhánh của công nghệ trí tuệ nhân tạo nhằm cung cấp những công cụ có thể cải thiện khả năng phân tích dựa trên những sự kiện xảy ra trước đó. Trong mảng phân tích dữ liệu, Machine learning được sử dụng để tạo ra các mô hình và thuật toán để có để dự đoán kết quả. Khả năng thành công của HTSS có thể tăng bằng cách điều chỉnh các “biến số” có thế ảnh hưởng đến quá trình điều trị. Tuy nhiên, việc xác định mối liên quan giữa các “biến số” là một nhiệm vụ phức tạp dành cho người bác sĩ lâm sàng và chuyên viên phôi học. Vì vậy, những mô hình và thuật toán có khả năng dự đoán kết cục của việc điều trị là rất cần thiết giúp bác sĩ và bệnh nhân có thể đạt được tỉ lệ thành công cao hơn. Ngày nay, Machine learning trong lĩnh vực HTSS được phát triển và nghiên cứu ngày càng nhiều nhằm cung cấp cho các bác sĩ lâm sàng những thông tin hữu ích hơn để có được nhưng quyết định tốt hơn, từ đó giúp cải thiện tỉ lệ thành công của điều trị [@th29]. 

### So sánh kết quả IVF trước và sau khi có nghiên cứu

Trước khi áp dụng các can thiệp trong lĩnh vực YHSS trên người bệnh, các can thiệp nên được đánh giá về tính hiệu quả và an toàn. Tính hiệu quả của một can thiệp trong lĩnh vực YHSS được thể hiện bởi sự cải thiện về tỉ lệ trẻ sinh sống (LBR) khi so sánh với các can thiệp khác thông qua thử nghiệm RCT. 

Năm 2019, Stocking K cùng cộng sự (2019) thực hiện nghiên cứu nhằm mục đích phân tích độ mạnh về mặt thống kê của các thử nghiệm lâm sàng ngẫu nhiên có đối chứng và phân tích tổng hợp để đánh giá hiệu quả của thử nghiệm trong YHSS. Như trước đó đã đề cập, hiệu quả của một can thiệp được đánh giá tốt nhất khi sử dụng thiết kế RCTs. Để có thể cung cấp được nhiều thông tin hữu ích, những thử nghiệm này nên đủ mạnh để có thể phát hiện được những ảnh hưởng lâm sàng nhỏ nhất. 

Nhóm nghiên cứu thực hiện đánh giá độ mạnh và sự chính xác của 199 nghiên cứu RCT và phân tích tổng hợp từ 109 bài phân tích của Cochrane. Những nghiên cứu được lựa chọn là các bài phân tích hệ thống được đăng bởi Cochrane với kết cục chính là tỉ lệ trẻ sinh sống. Đối với mỗi phân tích hệ thống cho kết quả là LBR (hoặc tỉ lệ thai diễn tiến), RCT có cỡ mẫu lớn nhất trong phân tích hệ thống đó được nhóm nghiên cứu tính toán độ mạnh để phát hiện sự cải thiện về LBR. Hơn nữa, khoảng tin cậy 95% (95% CI) được sử dụng để ước tính hiệu quả của điều trị trong phân tích hệ thống hoặc RCT, nhằm đánh giá sự chính xác của kết quả của nghiên cứu được phân tích. Đối với mỗi kết cục trong các RCT và phân tích tổng hợp, nhóm nghiên cứu tính toán độ mạnh để có thể phát hiện sử cải thiện LBR từ 1 điểm phần trăm (percentage point - pp) đến 25 pp, với tốc độ tăng là 0.5 pp, và sử dụng phân tích tiêu chuẩn dành cho biến nhị phân (kiểm định chi-squared hoặc Z test of proportions). Ví dụ sự cải thiện 5 pp nghĩa là sự tăng LBR từ 20% ở nhóm chứng lên 25% ở nhóm điều trị. Sau đó, nhóm nghiên cứu thực hiện tổng kết độ mạnh của các RCT/phân tích hệ thống bằng cách sử dụng thống kê mô tả, bao gồm tỉ lệ các RCT/phân tích hệ thống có thể đạt được độ mạnh 80% và 90% để phát hiện được sự cải thiện trong LBR. 

Kết quả ghi nhận trung bình độ mạnh của các RCT cho kết quả cải thiện LBR 5% trở lên sau can thiệp (ví dụ từ 25% lên 30%) là 13% (8–21%) và 16% (9–33%) đối với các phân tích hệ thống. Không có RCT nào và chỉ có 2% các phân tích hệ thống đạt được 80% độ mạnh để có thể phát hiện sự cải thiện 5 pp về LBR. Nhóm tác giả ghi nhận có 28% các bài phân tích trên Cochrane không có dữ liệu về trẻ sinh sống (hoặc thai diễn tiến). Điều này có thể do hiệu quả của những thử nghiệm này đã bị loại trừ trong giai đoạn sớm hoặc nghiên cứu thí điểm (pilot study) vì can thiệp không làm thay đổi những yếu tố có thể ảnh hưởng đến LBR (ví dụ số noãn chọc hút được hay chất lượng phôi). Như vậy, Stocking K. cùng cộng sự đã chứng minh rằng lĩnh vực YHSS hiện đang thiếu những nghiên cứu có khả năng phát hiện sự cải thiện thực tế về LBR. Tuy nhiên, các nghiên cứu RCT và phân tích tổng hợp là những thành phần không thể thiếu để đánh giá tính hiệu quả của những can thiệp trong lĩnh vực vô sinh hiếm muộn. Trong tương lai cần nhiều chiến lược để cải thiện bằng chứng và kêu gọi sự cộng tác để tập trung vào những câu hỏi nghiên cứu cốt lõi nhất [@th05].

### Kết luận

Như vậy, nghiên cứu khoa học là động lực phát triển cho y khoa nói chung và lĩnh vực HTSS nói riêng. Trên thế giới, số lượng các nghiên cứu có chất lượng cao được đăng trong các tạp chí không thuộc lĩnh vực HTSS và có yếu tố ảnh hưởng cao ngày càng nhiều. Cùng với sự công nhận rộng rãi của thế giới dành cho HTSS, Việt Nam cần có nhiều hơn những nghiên cứu có chất lượng cao, đặc biệt là các RCT. Lĩnh vực HTSS tại nước ta có nhiều thuận lợi để thực hiện NCKH như nguồn dữ liệu nhiều và số lượng bệnh nhân điều trị nhiều. Vì vậy trong tương lai, Việt Nam có cơ hội rất lớn để phát triển NCKH trong lĩnh vực HTSS. 

## Giới thiệu về giáo trình

### Ý tưởng về một giáo trình thống kê chuyên dụng cho nghiên cứu HTSS

Cho đến nay trong trường Đại học Y khoa, Thống kê vẫn luôn được giảng dạy như một môn học tổng quát và tách biệt với các chuyên khoa lâm sàng. Ngay cả trong giai đoạn đào tạo sau đại học bao gồm nội trú, chuyên khoa cấp 2, nghiên cứu sinh Thạc sĩ và Tiến sĩ, khi các bạn bác sĩ đã định hướng rất rõ về chuyên môn lâm sàng và đang theo đuổi các đề tài nghiên cứu chuyên biệt, thì họ vẫn phải học về Thống kê một cách chung chung. Hệ quả là khi bắt tay vào thực hành nghiên cứu lâm sàng, các bạn bác sĩ gặp nhiều trở ngại khi xác định công cụ thống kê phù hợp để giải quyết một số vấn đề đặc thù trong chuyên khoa của mình. 

Trong bối cảnh này, chúng tôi muốn thử nghiệm một cách thức tiếp cận mới – đó là xây dựng một giáo trình thống kê chuyên dụng cho nghiên cứu Hỗ trợ sinh sản, dành riêng cho bác sĩ Sản Phụ khoa. 

Không phải ngẫu nhiên và tùy hứng khi chúng tôi chọn chuyên ngành Sản Phụ khoa để làm thí điểm cho cách học và thực hành thống kê mới này, mà điều này chỉ là sự kế thừa truyền thống về mối quan hệ tương trợ tốt đẹp giữa ngành Sản Phụ khoa và ngành Thống kê [@bland1997]. Thật vậy, khi tham khảo y văn ngành Sản Phụ khoa từ thập niên 1930 đến giai đoạn hiện đại ta sẽ nhìn thấy rõ tiến trình đồng hành phát triển và cộng hưởng tích cực của cả hai chuyên ngành khoa học này. 

Một mặt, ngành thống kê cung cấp phương tiện cho bác sĩ Sản Phụ khoa giải quyết hiệu quả hơn các câu hỏi lâm sàng: Từ chỗ những nghiên cứu mô tả đơn giản và thô sơ, không áp dụng bất cứ phép kiểm thống kê nào vào những năm 1930-1945, phân tích thống kê trở thành một nội dung quan trọng chiếm tỷ lệ cao dần trong phần Phương pháp nghiên cứu. Theo một khảo sát của tác giả Khan và cs năm 1999, tỷ lệ bài báo khoa học ngành Sản Phụ khoa ứng dụng mô hình hồi quy logistic đã không ngừng gia tăng theo thời gian [@khan1999]; từ 1,7% năm 1985 lên 2.8% năm 1990 và 6.5% năm 1995 (hiện nay tỷ lệ này cao hơn 23%, theo tác giả ghi nhận vào năm 2021). 

Mặt khác, Sản Phụ khoa là chuyên ngành có một truyền thống về quan điểm cởi mở trong việc dung nạp những kỹ thuật thống kê tiên tiến và phi chính thống. Thí dụ, đến tân cuối thập niên 1990 khi chuyên ngành Nội khoa hô hấp vẫn còn dùng những mô hình hồi quy tuyến tính rất thô sơ để ước lượng giá trị tham chiếu cho dung tích phổi hay lưu lượng thông khí, thì ngay từ thập niên 1970 Sản Phụ khoa đã vận dụng những kỹ thuật thống kê rất tiến bộ để khảo sát diễn biến của các hormone sinh sản và nhiều biomarker huyết động học nhau thai, quy luật tăng trưởng của thai nhi, bao gồm quy luật phân phối logarit normal, Gamma, mô hình hồi quy phi tuyến tính với hàm đa thức... 

Trong một số hoàn cảnh, chính Sản Phụ khoa đã đặt ra những bài toán thống kê độc đáo, dẫn đến sự phát triển những phương pháp thống kê chuyên biệt, thí dụ các mô hình hồi quy phân vị mô tả quy luật tăng trưởng của thai nhi và trẻ sơ sinh, cũng như bài toán phân tích thời gian sự kiện là một dấu ấn độc đáo của ngành Sản Phụ khoa, mô hình hồi quy negative binomial để ước lượng số lượng noãn trong chu kỳ thụ tinh nhân tạo (ART calculator), vv. 

Một động lực khác thúc đẩy chúng tôi thực hiện giáo trình này, đó là tiếp cận kiến thức, kỹ năng thống kê là một nhu cầu thiết yếu của các anh chị em bác sĩ lâm sàng. Hiện nay vẫn còn tồn tại nhiều hạn chế về mặt bằng trình độ thống kê trong giới bác sĩ Sản Phụ khoa và hiện trạng này là phổ biến ngay cả ở các nước có nền giáo dục đại học và y học phát triển. Theo một cuộc khảo sát vào năm 2011 của nhóm tác giả Anderson và cs trên 4713 bác sĩ nội trú Sản Phụ khoa tại Hoa kỳ [@anderson2013], chỉ có 26% có khả năng định nghĩa đúng khái niệm « positive predictive value » và chỉ có 42% hiểu đúng ý nghĩa của giá trị p. Có đến 37% bác sĩ nội trú Sản Phụ khoa cho biết không được huấn luyện bài bản về kỹ năng đọc hiểu thống kê, số còn lại phần lớn chỉ tự học hoặc thông qua các buổi bình luận y văn. 

Trong một nghiên cứu khác của Welch và cs vào năm 1994 [@welch1996] cho riêng tờ báo American Journal of Obstetrics and Gynecology (AJOG), chỉ có 30.3% số bài báo trình bày một kế hoạch phân tích có phẩm chất tốt, trong khi vẫn còn 31.7% công bố đã áp dụng kỹ thuật phân tích thống kê không phù hợp và nhiều bài trong số này phạm những sai lầm nghiêm trọng về suy luận thống kê. Khi khảo sát lại một lần nữa sau thời gian 5 năm [@welch2002], các tác giả nhận thấy đã có sự cải thiện đáng kể về tỷ lệ phân tích thống kê có phẩm chất tốt (56.4% so với 30.3%). Kết quả này cho thấy quy trình bình duyệt ngày càng khắt khe và mức độ cạnh tranh cao đã loại bỏ bớt những bài báo khoa học có phẩm chất kém. Điều này gợi ý rằng kỹ năng thống kê có vai trò rất quan trọng quyết định khả năng công bố được nghiên cứu trên các tờ báo danh tiếng. 

Cuối cùng, chuyên đề hỗ trợ sinh sản được tác giả lựa chọn làm lộ trình vì tính độc đáo và thú vị của nó. Ngay cả với một người có kinh nghiệm thực hành thống kê y học hơn 12 năm, tác giả cũng bị choáng ngợp trước mức độ phức tạp của bài toán thống kê trong nghiên cứu HTSS. Tính chất phức tạp này bao gồm hai vấn đề:

+ Quy trình thụ tinh nhân tạo diễn ra qua nhiều công đoạn và đặt ra nhiều loại kết cục cần được khảo sát hơn bất cứ chuyên khoa nào khác. Theo quy ước, một thử nghiệm lâm sàng có thể cần ước lượng từ 5 đến 10 loại kết cục. Những kết cục này có bản chất đa dạng : số đếm (noãn, phôi), tỷ lệ (khả năng trưởng thành, thụ tinh, phôi được chuyển), nhị giá (khả năng đạt thai sinh hóa, thai lâm sàng, thai diễn tiến, sinh nở thành công). 

+ Bài toán thống kê trong nghiên cứu HTSS diễn ra trong một hệ thống tương tác phức tạp giữa nhiều yếu tố gây nhiễu, hiệp biến, và sinh ra một chuỗi kết quả có tính chất kế thừa và phụ thuộc lẫn nhau. Dữ liệu lại thường là hồi cứu nên cần những phương pháp can thiệp thích hợp để vô hiệu hóa hiệu ứng nhiễu của các hiệp biến và yếu tố nền. Mặt khác, ngay cả thiết kế RCT cũng không thể loại bỏ hoàn toàn những hiệp biến phát sinh ra sau giai đoạn phân nhóm ngẫu nhiên. 

Do đó, một phân tích thống kê chính xác cho dữ liệu nghiên cứu HTSS đòi hỏi kiến thức sâu rộng về lý thuyết xác suất, nhiều loại mô hình thống kê chuyên biệt như GLM, GLMM, GEE, được định hướng bằng kiến thức y học chuyên ngành. Những kiến thức và kỹ năng này đều vượt ra khỏi giới hạn của thống kê y học thường quy. 

Nhóm tác giả hy vọng giáo trình này sẽ trở thành một cầu nối giữa hai thế giới: Thống kê và Sản Phụ khoa lâm sàng, giúp cho cả bác sĩ/nghiên cứu sinh chuyên ngành Hỗ trợ sinh sản và chuyên viên thống kê nhận ra tính chất tương hợp và liên hệ kì thú giữa các hiện tượng, quá trình trong thí nghiệm thụ tinh nhân tạo và các quy luật phân phối xác suất, mô hình hồi quy chuyên biệt. Từ đó, họ tìm được ngôn ngữ chung, có thể phiên dịch các câu hỏi nghiên cứu thực tiễn thành bài toán thống kê, và vận dụng được công cụ thống kê phù hợp cho vấn đề lâm sàng. 

### Mục tiêu học tập

Qua tác phẩm này, các tác giả mong muốn hướng dẫn người đọc đạt được những thành quả như sau: Về mặt lý luận và tư tưởng, các bạn bác sĩ và chuyên viên thống kê sẽ nhận ra được những điểm độc đáo, thú vị của dữ liệu và các bài toán thống kê trong nghiên cứu hỗ trợ sinh sản mà ta không thể gặp trong bất cứ chuyên khoa lâm sàng nào khác. Các bạn cũng sẽ nhận ra bản chất của các loại kết cục khác nhau trong nghiên cứu thụ tinh nhân tạo, phiên dịch được chúng sang ngôn ngữ xác suất và áp dụng đúng loại phân phối, mô hình phù hợp. 

Qua việc thực hành các thí nghiệm trong sách, khả năng phân tích thống kê bằng ngôn ngữ R của người học sẽ đạt trình độ nâng cao, tương đương với một nhân viên phân tích dữ liệu chuyên nghiệp. Những kỹ năng này bao gồm phong cách viết R codes hiện đại, việc nắm vững quy trình suy diễn thống kê dựa vào mô hình tuyến tính tổng quát (generalized linear model), tận dụng ưu thế về đồ họa thống kê của R để tạo ra biểu đồ ấn tượng và làm quen với phương pháp machie learning khả diễn … để thay thế cho các công cụ thống kê cổ điển và kiểm định rời rạc. Đặc biệt, chúng tôi đề xuất nhiều ý tưởng và kế hoạch phân tích chưa từng được áp dụng trong y văn của chuyên ngành hỗ trợ sinh sản, với hy vọng và niềm tin về tương lai phát triển của y học hàn lâm của nước ta.

### Nội dung và quy ước trình bày

Cấu trúc của giáo trình được thiết kế theo dạng module gồm 9 chương hoàn toàn độc lập với nhau. Các bạn có thể khởi hành ở bất cứ chương nào, cũng như đọc theo trình tự ngẫu nhiên tùy ý thích. Mỗi chương sẽ giới thiệu về một phương pháp thống kê khác nhau, tương ứng với một mục tiêu nghiên cứu chuyên biệt. Sau khi đọc xong và tổng hợp lại, các bạn sẽ nhận ra mình đã đi qua tất cả các chặng trên hành trình tương ứng với một chu kì thụ tinh nhân tạo và nắm vững các giải pháp thống kê thích hợp cho tất cả các loại kết cục lâm sàng ở mỗi công đoạn.

Nội dung của mỗi chương sẽ được trình bày như một nghiên cứu lâm sàng thu nhỏ và dựa trên dữ liệu thực nghiệm có thực, bao gồm bối cảnh của thí nghiệm, mục tiêu của nghiên cứu, nội dung của kế hoạch phân tích, lược giảng lý thuyết về phương pháp thống kê, bản hướng dẫn thi hành từng bước, dẫn đến kết quả, diễn giải kết quả, bàn luận và cuối cùng là một bản tóm tắt ngắn gọn những thông điệp dùng làm hành trang.

Giáo trình này được biên soạn theo tiêu chí thực dụng, nên chúng tôi cố gắng cân bằng giữa nội dung lý thuyết về thống kê và kỹ năng thực hành. Trong mỗi chương sách, hàm lượng lý thuyết được giản lược tối thiểu để các bạn bác sĩ lâm sàng hiểu được khái niệm thống kê, không bị phân tâm bởi các thuật toán, công thức phức tạp nhưng vẫn nắm vừa đủ thông tin về kỹ thuật để có thể trình bày lại trong luận văn hoặc bài báo khoa học của mình.

Nội dung thực hành được biên soạn như công thức nấu ăn hay sổ tay phòng thí nghiệm, ở mức độ chi tiết đủ cho người học cảm thấy dễ chịu và thoải mái như được một người bạn cầm tay hướng dẫn trước máy tính. Kết quả sẽ hiển thị ngay cho mỗi bước và được diễn giải một cách rõ ràng nhưng chuẩn mực về thuật ngữ và văn phong khoa học.

Nhằm thích ứng với hai nhóm đối tượng người đọc khác nhau với những nhu cầu học tập khác nhau, bao gồm (1) nhóm bác sĩ lâm sàng chỉ cần một tài liệu chuyên khảo, nhằm tìm hiểu về thuật ngữ, khái niệm thống kê, cách thức diễn giải kết quả và diễn đạt trong văn bản khoa học, nhưng không có nhu cầu đi sâu vào thực hành phân tích dữ liệu; và (2) nhóm chuyên viên thống kê hoặc bác sĩ nghiên cứu sinh có nhu cầu học lập trình thống kê trong ngôn ngữ R để có thể tự phân tích dữ liệu cho bản thân, chúng tôi quyết định không trình bày nội dung mã lập trình trong sách in, nhưng bạn đọc có thể dễ dàng truy cập dữ liệu và mã lập trình cho các thí nghiệm trong sách qua liên kết sau đây: https://github.com/kinokoberuji/Data_analysis_IVF

### Nguồn gốc của dữ liệu

Mỗi thí nghiệm trong giáo trình này được tác giả tiến hành trên một phiên bản dữ liệu đã qua biên tập và làm sạch từ dữ liệu gốc. Việc biên tập bao gồm giản lược cấu trúc, trích xuất tập hợp biến số hoặc phân nhóm thích hợp với bài toán thống kê chuyên biệt từ một hay nhiều bộ dữ liệu gốc. Tất cả dữ liệu gốc đều được tác giả của chúng chia sẻ công khai cho cộng đồng (public data), và đều là dữ liệu có thực từ những nghiên cứu lâm sàng chuyên ngành hỗ trợ sinh sản trong giai đoạn 2018-2022 tại Trung Quốc và một số quốc gia Châu Âu khác. Thông tin chi tiết về nguồn gốc của những bộ dữ liệu này được trình bày dưới đây:

1) Bộ dữ liệu từ nghiên cứu "Blastocyst age, expansion, trophectoderm morphology, and number cryopreserved are variables predicting clinical implantation in single blastocyst frozen embryo transfers in freeze-only-IVF" của nhóm tác giả Kevin Coetzee, Kemal Ozgur và cộng sự, với mục tiêu nhằm xác định vai trò những thông số phẩm chất và hình thái phôi cho phép dự đoán khả năng thụ thai lâm sàng trong các trường hợp chuyển phôi bằng kỹ thuật frozen embryo transfers (FET) trong chu kỳ IVF. Nghiên cứu được công bố ngày 16/2/2021 tại: Journal of Assisted Reproduction and Genetics (2021) 38:1077–1087. Dữ liệu có thể truy cập tại: https://data.mendeley.com/datasets/5925df99w9/1 (DOI: 10.17632/5925df99w9.1)

2) Bộ dữ liệu của nhóm tác giả Sandro C. Esteves và cộng sự, dùng trong nghiên cứu "Validation of ART Calculator for Predicting the Number of Metaphase II Oocytes Required for Obtaining at Least One Euploid Blastocyst for Transfer in Couples Undergoing in vitro Fertilization/Intracytoplasmic Sperm Injection", được công bố ngày 24/1/2020 tại: Front Endocrinol (Lausanne). 2019; 10: 917. doi: 10.3389/fendo.2019.00917. Đây là nghiên cứu đa trung tâm với mục tiêu kiểm nghiệm mô hình tiên lượng ART calculator của nhóm tác giả có khả năng dự đoán số lượng noãn MII tối thiểu cần thu thập để đạt được ít nhất một phôi khả dụng trên bệnh nhân tiến hành phương pháp thụ tinh trong ống nghiệm. Dữ liệu được công khai và có thể truy cập từ trang web của bài báo: https://www.frontiersin.org/articles/10.3389/fendo.2019.00917/full

3) Dữ liệu của nhóm tác giả Lu Guan và cộng sự dùng trong nghiên cứu "The effect of mildly stimulated cycle versus artificial cycle on pregnancy outcomes in overweight/obese women with PCOS prior to frozen embryo transfer: a retrospective cohort study". Đây là một nghiên cứu hồi cứu nhằm so sánh kết cục thai kì giữa phương pháp kích thích nhẹ sử dụng Letrozole và chu kỳ nhân tạo trước khi tiến hành chuyển phôi FET ở phụ nữ mắc hội chứng buồng trứng đa nang (PCOS). Bài báo được công bố năm 2022 trên tờ báo: BMC Pregnancy and Childbirth (2022) 22:394: (https://doi.org/10.1186/s12884-022-04728-6), dữ liệu được công khai và có thể truy cập từ trang web của bài báo hoặc từ kho dữ liệu fishare:
https://figshare.com/articles/dataset/Additional_file_1_of_The_effect_of_mildly_stimulated_cycle_versus_artificial_cycle_on_pregnancy_outcomes_in_overweight_obese_women_with_PCOS_prior_to_frozen_embryo_transfer_a_retrospective_cohort_study/19728623

4) Bộ dữ liệu mở từ nghiên cứu "Prediction of live birth and cumulative live birth rate in a general infertile population treated with freeze-all-IVF" của nhóm tác giả Kevin Coetzee, Kemal Ozgur và cộng sự, với mục tiêu khảo sát mối liên hệ giữa các thông số can thiệp với tỷ lệ tạo phôi và tỷ lệ inh sống tích lũy (cumulative live birth) trong chu kì IVF trên quần thể phụ nữ vô sinh tổng quát. Nghiên cứu được công bố ngày 21/2/2019 tại: J Assist Reprod Genet. 2019 Apr; 36(4): 685–696.doi: 10.1007/s10815-019-01422-z. Dữ liệu có thể truy cập tại: https://data.mendeley.com/datasets/xy2t2cxm8g (DOI: 10.17632/xy2t2cxm8g.1)

5) Dữ liệu của nhóm tác giả Qianwen Xi và cộng sự dùng trong nghiên cứu "Comparison Between PPOS and GnRHa-Long Protocol in Clinical Outcome with the First IVF/ICSI Cycle: A Randomized Clinical Trial". Một nghiên cứu hồi cứu nhằm khảo sát hiệu quả của phác đồ progestin-primed ovarian stimulation (PPOS) so với phác đồ đối vận GnRH kéo dài. Bài báo được công bố vào tháng 3/2020 tại Clin Epidemiol. 2020; 12: 261–272. (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7060798/). Dữ liệu công khai và có thể truy cập tại: https://figshare.com/articles/dataset/dataset/10253063/3

6) Dữ liệu của nhóm tác giả Lu Li và cộng sự dùng trong nghiên cứu "Which Factors Are Associated With Reproductive Outcomes of DOR Patients in ART Cycles: An Eight-Year Retrospective Study", nhằm mục tiêu khảo sát các yếu tố liên quan đến kết cục sinh sản ở nhóm đối tượng phụ nữ hiếm muộn giảm dự trữ buồng trứng và vai trò của AMH đối với dự kết quả chu kỳ IVF ở nhóm bệnh nhân này. Bài báo được công bố ngày 23/6/2022 tại : Front Endocrinol (Lausanne) 2022;13:796199 (doi: 10.3389/fendo.2022.796199). Dữ liệu công khai và có thể truy cập từ trang web của bài báo: https://www.frontiersin.org/articles/10.3389/fendo.2022.796199/full 

7) Dữ liệu của nhóm tác giả Yanjun Zheng và cộng sự dùng trong nghiên cứu "Ovarian Sensitivity Decreased Significantly in Patients With Insulin Resistance Undergoing in vitro Fertilization and Embryo Transfer". Mục tiêu nhằm khám phá mối liên hệ giữa chỉ số nhạy cảm buồng trứng (OSI) và các thông số truyền thống về đáp ứng buồng trứng và khảo sát mối quan hệ giữa OSI và rối loạn kháng-insulin ở phụ nữ với hội chứng PCOS. bài báo được công bố trên tờ Front Physiol. 2022 Mar 11;12:809419 (doi: 10.3389/fphys.2021.809419).Dữ liệu công khai và có thể truy cập từ trang web của bài báo: https://www.frontiersin.org/articles/10.3389/fphys.2021.809419/full

8) Bộ dữ liệu của nhóm tác giả Mathilde Bourdon và cộng sự, dùng trong nghiên cứu "The deferred embryo transfer strategy improves cumulative pregnancy rates in endometriosis-related infertility: A retrospective matched cohort study". Mục tiêu nhằm so sánh kết cục hỗ trợ sinh sản giữa 2 kỹ thuật chuyển phôi đông (Def-ET) và phôi tươi (ET) ở đối tượng phụ nữ hiếm muộn kèm theo bệnh lý nội mạc tử cung. Bài báo công bố trên tờ PLOSOne ngày 19/4/2019:  https://doi.org/10.1371/journal.pone.0194800. Dữ liệu công khai và có thể truy cập tại: https://figshare.com/articles/dataset/The_deferred_embryo_transfer_strategy_improves_cumulative_pregnancy_rates_in_endometriosis-related_infertility_A_retrospective_matched_cohort_study/6116915?file=11029871

### Về một số thư viện R quan trọng

Trong giáo trình này các tác giả đã sử dụng một số thư viện/gói công cụ (packages) như sau: 

1) Tidyverse

Đây là một hệ sinh thái được phát triển bởi RStudio [@tidyverse], tập hợp các gói với công dụng xử lý và phân tích dữ liệu trong R. Mỗi gói trong tidyverse đều có mục đích riêng biệt, nhưng chúng lại được thiết kế để tương tác tốt với nhau, giúp người dùng xử lý và phân tích dữ liệu một cách dễ dàng và hiệu quả hơn, bao gồm: Xử lý và chuyển đổi dữ liệu (tidyr, dplyr), đồ họa thống kê (ggplot2 [@wickham2016]), đọc và ghi dữ liệu (readr, readxl, writexl), lập trình hàm và xử lý dữ liệu song song (purrr). 

Ngoài ra, tidyverse cũng định hình phong cách viết R codes hiện đại dựa trên hệ thống nguyên tắc về "tidy data" được lập ra bởi Hadley Wickham, tác giả chính của tidyverse. Theo khái niệm này, dữ liệu sẽ được tổ chức theo các cột (variables) và các hàng (observations), mỗi hàng là một quan sát và mỗi cột là một thuộc tính của quan sát đó. Việc sử dụng "tidy data" giúp cho việc xử lý và phân tích dữ liệu trở nên dễ dàng và rõ ràng hơn.

2) GAMLSS

GAMLSS (Generalized Additive Models for Location, Scale and Shape) [@stasinopoulos2017] [@rigby2020] là một thư viện trong ngôn ngữ lập trình R được phát triển bởi các nhà thống kê Robert Rigby và Mikis Stasinopoulos và được giới thiệu vào năm 2005, với công dụng xây dựng các loại mô hình tuyến tính tổng quát và phi tuyến tính cho rất nhiều quy luật phân bố xác suất và cho phép ước lượng riêng biệt từng tham số của một quy luật phân phối. Nhờ sử dụng gamlss mà ta có thể thực hiện các ý tưởng về mô hình GLM cho các phân phối Negative binomial, Binomial, Gamma, vv cho các loại kết cục lâm sàng khác nhau trong nghiên cứu IVF.

3) Marginaleffects 

Đây là một thư viện quan trọng khác sẽ được sử dụng thường xuyên trong nhiều thí nghiệm. Thư viện marginaleffects [@marginal] hỗ trợ ước lượng và kiểm định các hiệu ứng biên (marginal effects) trong quá trình suy diễn thống kê dựa trên nội dung các mô hình hồi quy. Thư viện này tương thích với hơn 70 gói công cụ về mô hình hồi quy trong R, cho phép suy luận thống kê cho tất cả các mô hình thống kê phổ biến, bao gồm GLM, survival, GLMM và GEE.

4) Tidymodels

Tidymodels là một hệ sinh thái các gói công cụ được phát triển bởi Max Kuhn, với ứng dụng thực hiện các thí nghiệm Machine learning trong R [@tidymodels] [@kuhn2022]. Ý tưởng của tidymodels là cung cấp một khung công cụ phổ quát, đơn giản và dễ sử dụng để thực hiện một quy trình xây dựng các mô hình machine learning dựa trên dữ liệu. Quy trình này bao gồm các bước tiền xử lý dữ liệu, lựa chọn biến, xây dựng và đánh giá mô hình. Tidymodels cũng cung cấp các hàm dễ sử dụng để tinh chỉnh và tối ưu hóa các tham số của mô hình. Nó có tính nhất quán và phổ quát, khi đặt ra một quy trình, quy luật cú pháp R codes đồng nhất, giảm thiểu sự phụ thuộc vào cú pháp chuyên biệt, phân tán của các gói phần mềm khác.

### Yêu cầu về kiến thức và kỹ năng cơ bản

Hầu hết những phương pháp thống kê được giới thiệu trong tài liệu này vượt ra ngoài giới hạn của kiến thức thống kê y học thường quy, tuy nhiên nhóm tác giả sẽ cố gắng trình bày về chúng một cách đơn giản và dễ hiểu nhất có thể, dựa trên giả định rằng người đọc đã nắm vững kiến thức về xác suất và thống kê ở trình độ đại học y khoa (một số khái niệm cơ bản như hàm mũ, hàm logarit, phân phối xác suất, biến ngẫu nhiên, nguyên lý kiểm định giả thuyết vô hiệu, các trị số thống kê mô tả và ước lượng nguy cơ như OR, RR, khoảng tin cậy, một số dạng biểu đồ thống kê cơ bản và mô hình hồi quy tuyến tính).

Về kỹ năng lập trình thống kê, chúng tôi giả định rằng người đọc đã từng tiếp cận và sử dụng qua ngôn ngữ R [@R] ở mức độ khái niệm và cơ bản. Yêu cầu duy nhất là các bạn đã biết cách sử dụng R console hoặc giao diện R-Studio, với một số thao tác cơ bản như cài đặt và gọi R package, tải dữ liệu .csv. Trong quá trình thực hành các bạn sẽ được hướng dẫn chi tiết mọi công đoạn, hầu hết trường hợp ta chỉ đơn giản làm việc ở mức độ ứng dụng thư viện (package) có sẵn. Chỉ một số ít trường hợp yêu cầu viết hàm hoặc vòng lặp nhưng các bạn hoàn toàn có khả năng đọc hiểu và tái sử dụng mã lập trình do tác giả cung cấp.

### Khả năng tương thích với chuyên khoa lâm sàng khác

Tài liệu này được biên soạn dành riêng cho các bác sĩ Sản Phụ khoa và chuyên ngành Hỗ trợ sinh sản, vì vậy hiệu quả thực hành và ứng dụng sẽ đạt tối ưu cho các đồng nghiệp này. Tuy nhiên vì thống kê là một môn khoa học phổ quát, nên bằng tư duy trừu tượng và sáng tạo, người đọc từ một chuyên khoa khác, thậm chí không công tác trong ngành Y khoa vẫn có thể tiếp thu được một số ý tưởng và kỹ năng từ các thí nghiệm trong sách và vận dụng cho những vấn đề của bản thân. Thí dụ: mô hình hồi quy Negative binomial có thể áp dụng khảo sát kết cục là số đợt kịch phát của bệnh phổi tắc nghẽn mạn tính hay hen phế quản cho chuyên khoa hô hấp, mô hình hồi quy Gamma có thể dùng khảo sát một biomarker trong chuyên khoa Tim mạch, ý tưởng về Machine learning khả diễn và phân tích thành phần chính PCA có thể áp dụng cho nghiên cứu sinh học phân tử, vv.
